### ISSUE TITLE
lot of defunt process in openvas docker service

### ISSUE THREAD

**Issue by konvergence** [admirito/gvm-containers#11]
Hi,

there a lot of  defunt process in the openvas docker service

```
root@2bb3b43c986f:/# ps -ef | grep defunct | wc -l
464
```

this is due to docker with python.
If you start the pid 1 process with tini, it manage well the process termination

update the Dockerfile like this

```
# Add Tini
ARG TINI_VERSION="v0.18.0"
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

ENTRYPOINT ["/tini", "--", "bash", "/usr/local/bin/docker-entrypoint.sh" ]
```

you can check my pull request

**Comment by admirito** [comment]
I have accepted the GH-10 pull request. Thnak you for your contribution.
