### ISSUE TITLE
How to set it up on Manjaro

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [admirito/gvm-containers#12]
Hello,
Hi I would like to install it on my Manjaro KDE distro but I do not have any knowledge of docker or GVM can you please tell me how can I begin setting this up and running on manjaro.

**Comment by admirito** [comment]
If you have already installed docker and docker-compose (not exactly sure how in Manjaro, maybe `sudo pacman -S docker`) the instructions to bring up GVM is in the README file.
