### ISSUE TITLE
xml missing from the gvm image

### ISSUE THREAD

**Issue by pomac303** [admirito/gvm-containers#19]
gvmd_1          | sh: 1: xml_split: not found
gvmd_1          | md manage:WARNING:2020-10-07 09h52.47 utc:44204: split_xml_file: system failed with ret 32512, 127, xml_split -s40Mb split.xml && head -n 2 split-00.xml > head.xml && echo '</cpe-list>' > tail.xml && for F in split-*.xml; do    tail -n +3 $F    | head -n -1    | cat head.xml - tail.xml    > new.xml;    mv new.xml $F;    done

**Comment by legolasthehansy** [comment]
Can confirm this issue exists on our as well

`gvmd_1          | waiting for the database...
gsad_1          | gsad main:MESSAGE:2020-12-24 18h08.29 utc:1: Starting GSAD version 9.0.1
gvmd_1          | md   main:MESSAGE:2020-12-24 18h08.29 utc:1:    Greenbone Vulnerability Manager version 9.0.1 (DB revision 221)
gvmd_1          | md manage:WARNING:2020-12-24 18h08.29 utc:1: database must be initialised from scanner
gvmd_1          | util gpgme:MESSAGE:2020-12-24 18h08.30 utc:1: Setting GnuPG dir to '/var/lib/gvm/gvmd/gnupg'
gvmd_1          | util gpgme:MESSAGE:2020-12-24 18h08.30 utc:1: Using OpenPGP engine version '2.2.19'
gvmd_1          | md manage:   INFO:2020-12-24 18h08.30 utc:38: update_scap: Updating data from feed
gvmd_1          | md manage:   INFO:2020-12-24 18h08.30 utc:38: Updating CPEs
gvmd_1          | sh: 1: xml_split: not found
gvmd_1          | md manage:WARNING:2020-12-24 18h08.31 utc:38: split_xml_file: system failed with ret 32512, 127, xml_split -s40Mb split.xml && head -n 2 split-00.xml > head.xml && echo '</cpe-list>' > tail.xml && for F in split-*.xml; do    tail -n +3 $F    | head -n -1    | cat head.xml - tail.xml    > new.xml;    mv new.xml $F;    done
gvmd_1          | md manage:WARNING:2020-12-24 18h08.31 utc:38: split_xml_file: and failed to chdir back
gvmd_1          | md manage:WARNING:2020-12-24 18h08.31 utc:38: update_scap_cpes: Failed to split CPEs, attempting with full file`

**Comment by mcree** [comment]
should be fixed in master
