### ISSUE TITLE
Cannot read property 'scan_run_status' of undefined

### ISSUE THREAD

**Issue by itsouvalas** [admirito/gvm-containers#26]
Steps to reproduce:

* Use the [default setup steps](https://github.com/admirito/gvm-containers/blob/master/README.org)
* Start a Task and visit the report by clicking the progress bar under Status or the number under Report

Expected behavior:

* For the report in progress to be displayed

Current behavior

* fails to display with the following error:
`Cannot read property 'scan_run_status' of undefined`

This is discussed [here](https://github.com/greenbone/gsa/issues/2389) and has been addressed in later commits.

Workaround (provided above):

* Get a listing of running containers
`docker ps -a`
* locate the `CONTAINER ID` that matches `admirito/gvmd:20` and connect to it
`docker exec -ti 12ea9bdf9b61 /bin/bash` (replace with your ID)
* change permissions
`chmod 755 /var/lib/gvm/gvmd/report_formats/`

p.s.
Thanks for an amazing job!

**Comment by admirito** [comment]
Thnak you @itsouvalas 

I have used the mentioned  `chmod` command in the docker entrypoint to fix the issue.
