### ISSUE TITLE
Database is wrong version.

### ISSUE THREAD

**Issue by stef97** [admirito/gvm-containers#41]
After I oullled new version from GIT ,
I am unable to start GVM because the database is not being updated

Steps used are

docker-compose -f nvt-sync.yml -f cert-sync.yml -f scap-sync.yml -f gvmd-data-sync up
docker-compose up -d

The error is 

"
..
gvmd_1          | md manage:MESSAGE:2021-08-16 18h32.30 utc:21: check_db_versions: database version of database: 221
gvmd_1          | md manage:MESSAGE:2021-08-16 18h32.30 utc:21: check_db_versions: database version supported by manager: 233
gvmd_1          | Database is wrong version.
gsad_1          | gsad main:MESSAGE:2021-08-16 18h32.31 utc:1: Starting GSAD version 20.08.1
.."

Any help/ suggestions will be appreciated 

Thanks

**Comment by admirito** [comment]
The [database migration](https://github.com/admirito/gvm-containers/blob/cc03f9ab/gvmd/docker-entrypoint.sh#L29) will be only executed on the first execution of `gvmd` or if [FORCE_DB_INIT=1](https://github.com/admirito/gvm-containers/blob/cc03f9ab/gvmd/docker-entrypoint.sh#L24) environment variable is passed.

Also you can execute `gvmd --migrate` manually (you have to first bring down the containers):

```sh
docker-compose run gvmd gvmd --migrate
```

**Comment by admirito** [comment]
The new GVM-21 update @ 69fd528 add automatic migration every time the gvmd is running and no manual action is required after upgrade.
