### ISSUE TITLE
Missing latex packages for PDF report generation

### ISSUE THREAD

**Issue by abrom** [admirito/gvm-containers#5]
I was having some issues downloading the openvas reports as PDF (downloaded PDF was 0 bytes) and found the cause was some missing latex packages in the `gvmd` container. I resolved it with:

sudo docker exec -it gvmd /bin/bash
apt-get update
apt-get install -y texlive-latex-extra --no-install-recommends
apt-get install -y texlive-fonts-recommended

Not sure if that's necessarily something you'd want to include in the base install, but might be useful for others

**Comment by falconws** [comment]
I've confirmed this problem too.
@abrom 's workaround was effective(solve this problem).

I think these missing packages should be included Docker image.

**Comment by Fail-Unsafe** [comment]
[There was a change concerning the API](https://github.com/matrix-org/synapse/releases/tag/v1.32.0rc1)

> This release removes the deprecated GET /_synapse/admin/v1/users/<user_id> admin API. Please use the v2 API instead, which has improved capabilities.

**Comment by mcree** [comment]
should be fixed in master
