### ISSUE TITLE
gvm-postgres is not using entrypoints or uuid-ossp

### ISSUE THREAD

**Issue by apilynx** [admirito/gvm-containers#7]
This is rather a question than an issue because I am struggling to understand how this is working.

- How come there is no creation of an uuid-ossp extension on **gvm-postgres** which is needed for openvas?

- How does **gvm-postgres**'s docker-entrypoint.sh ever run if it is never copied in the Dockerfile altogether?

- "${FORCE_DB_INIT}" = "1" present in gvmd's entrypoint is only when building on top of older openvas versions with sqlite?

**Comment by admirito** [comment]
* I think the extension will be created by the gvmd itself.

* gvm-postgres is based on "postgres:12" as mentioned in the first line of Dockerfile:

```
FROM postgres:12
``` 
So we don't need to copy anything. If you don't change anything, it is exactly like the parent image. Everything including the entrypoint.

* `FORCE_DB_INIT` is just left for the user, so it can reinitialize the DB if he wishes.

Sorry for the late reply. As it is probably too late I will close the issue, to make things clean here!
